# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
  "discover",
  "cleaner",
  "command",
  "config",
  "logger",
  "screen",
  "utils",
  "server",
  "storage",
  "domain",
]
